### ISSUE TITLE
dont work

### ISSUE THREAD

**Issue by Grimtin10** [luminous-foundation/Luminosity#1]
👎 dont work
![funny cat](https://github.com/luminous-foundation/Luminosity/assets/20334046/75644d11-2ab2-4eb1-858c-d664b29418f4)

**Comment by Grimtin10** [comment]
![abitsilly](https://github.com/luminous-foundation/Luminosity/assets/20334046/deebe83e-310e-47ce-9f87-942decf23a08)

**Comment by Grimtin10** [comment]
![cate](https://github.com/luminous-foundation/Luminosity/assets/20334046/6114f79a-8103-443b-9f3b-07fdb5d2a8c0)

**Comment by YendisFish** [comment]
![Terry](https://github.com/luminous-foundation/Luminosity/assets/44734948/42ccb905-2749-4b5a-8a93-88dadd5ba7b1)

this is you rn

**Comment by YendisFish** [comment]
![00009-427041938](https://github.com/luminous-foundation/Luminosity/assets/44734948/77b5a476-392f-475e-ac00-ba2d4281aafc)

me rn
